# Generated by Django 5.1.3 on 2024-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewform',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reviewform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reviewform',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
